<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FFCI1MS4" ignored="5" name="Default test" tests="1" failures="1" timestamp="30 Dec 2021 06:42:34 GMT" time="13.851" errors="0">
  <testcase name="checkCoursesPageTest" time="3.991" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [https://test-connectedminds-expert.connectlab.ai/feeds/courses] but found [https://test-connectedminds-expert.connectlab.ai/feeds/trending]">
      <![CDATA[java.lang.AssertionError: expected [https://test-connectedminds-expert.connectlab.ai/feeds/courses] but found [https://test-connectedminds-expert.connectlab.ai/feeds/trending]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.connectedminds.expert.qa.test.HomePageTest.checkCoursesPageTest(HomePageTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkCoursesPageTest -->
  <testcase name="checkTrendingPageTest" time="0.0" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <ignored/>
  </testcase> <!-- checkTrendingPageTest -->
  <testcase name="checkSavedPageTest" time="0.0" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <ignored/>
  </testcase> <!-- checkSavedPageTest -->
  <testcase name="checkPostPageTest" time="0.0" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <ignored/>
  </testcase> <!-- checkPostPageTest -->
  <testcase name="checkArticleTest" time="0.0" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <ignored/>
  </testcase> <!-- checkArticleTest -->
  <testcase name="checkPodcastPageTest" time="0.0" classname="com.connectedminds.expert.qa.test.HomePageTest">
    <ignored/>
  </testcase> <!-- checkPodcastPageTest -->
</testsuite> <!-- Default test -->
